graphqlite_bundle:
  resource: '@GraphqliteBundle/Resources/config/routes.xml'

menu_maker:
  resource: '../src/Controller/'
  type: annotation

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
